<?php
// @generated by php-fn/di

namespace fn\Composer\DI;

class Invoker extends \DI\Container
{
    /**
     * @inheritdoc
     */
    public function __construct()
    {
        require_once __DIR__ . '/container-classes.php';
        $config = ContainerConfigurationFactory::create([], null, ...[]);
        parent::__construct(
            $config->getDefinitionSource(),
            $config->getProxyFactory(),
            $config->getWrapperContainer()
         );
    }
}
